### ISSUE TITLE
Make v2 (newgui) installable

### ISSUE THREAD

**Issue by tassaron** [djfun/audio-visualizer-python#68]
I am trying to resurrect this project because I'm still proud of the work I did on the `feature-newgui` branch. At the very least I would like to get the project working from that branch **mostly as-is** with critical bugs fixed.

I don't necessarily need any help with this, I'm just creating an issue to help track my progress.

@djfun How interested are you in merging `newgui` nowadays (given that it's been a while)? If you don't want it to replace the original then we could perhaps split this into a separate repo (with both of us having write permission). I don't mind either way.

The app works on Kubuntu 22.04 (my system) if I pip install it. I'm choosing to focus on that OS, and Windows 11, for the time being. I'm gonna try to get a py2exe (pip freeze?) type of distribution, then I'll test on Windows 10.

# To-Do List
- [ ] Create some tests of the Core at least -- these can be included with the app so people can run them to gather data to report bugs
- [x] Remove avconv support (that's vestigial code in my opinion)
- [x] In the error message that says the version of ffmpeg, inform the user that they need the GPL version. Tell them where to put the exe file or let them select a location.
- [x] Changing Color component to a gradient causes instant crash without an exception. Could be a segmentation fault in Qt but normally it would print an error message of some kind.
    - Happens on Windows 11 with Qt 5.15.2
    - Does not happen on Ubuntu 22.04 with Qt 5.15.3
        - Does happen on Ubuntu if using commandline mode! 
- [x] Fix "QThread destroyed while still running" at program exit
- [x] Ctrl+C may cause atexit module to raise an exception during exit, due to circular logic (the cleanup method is run twice)
- [x] Message about using Pillow-SIMD instead of Pillow should not appear on the Windows version because compiling stuff on Windows is impossible (lol, but seriously)
- [x] Sometimes the QUndoStack has an error during exit
- [ ]  Video Pipe seemingly does not send frames on Windows 11. Works on Ubuntu with same ffmpeg (4.4.1 GPL-licensed, compiled with gcc 11)

**Comment by djfun** [comment]
Hi @tassaron
well, if it works, I am happy to bring the branch to master. If someone wants to use the old version, they can still go back in the git history. Do you want to finish your to-do list first or how do you want me to proceed?

**Comment by tassaron** [comment]
We should make a GitHub release of the old version, so people can easily find it.

I would like to finish my to-do list first before merging. I want to understand the source of some bugs on Windows, and add more logging/testing so the code is more maintainable.

I'll make a pull request when I'm ready!
